name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Mocks
        run: go get github.com/golang/mock/mockgen@v1.4.4 && mockgen -destination pkg/mocks/manager/mock.go sigs.k8s.io/controller-runtime/pkg/manager Manager

      - name: Test
        run: go test ./... -coverprofile cover.out -timeout 30m
        env:
          CGO_ENABLED: 0
          GO111MODULE: on
          GOOS: linux
          GOARCH: amd64

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out